/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-04 at 23:36:33 UTC 
 * Modify at your own risk.
 */

package com.shawnkrecker.eventation.groupsubscribersendpoint;

/**
 * Service definition for Groupsubscribersendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GroupsubscribersendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Groupsubscribersendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the groupsubscribersendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://event-ation.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "groupsubscribersendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Groupsubscribersendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Groupsubscribersendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getGroupSubscribers".
   *
   * This request holds the parameters needed by the the groupsubscribersendpoint server.  After
   * setting any optional parameters, call the {@link GetGroupSubscribers#execute()} method to invoke
   * the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetGroupSubscribers getGroupSubscribers(java.lang.Long id) throws java.io.IOException {
    GetGroupSubscribers result = new GetGroupSubscribers(id);
    initialize(result);
    return result;
  }

  public class GetGroupSubscribers extends GroupsubscribersendpointRequest<com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers> {

    private static final String REST_PATH = "groupsubscribers/{id}";

    /**
     * Create a request for the method "getGroupSubscribers".
     *
     * This request holds the parameters needed by the the groupsubscribersendpoint server.  After
     * setting any optional parameters, call the {@link GetGroupSubscribers#execute()} method to
     * invoke the remote operation. <p> {@link GetGroupSubscribers#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetGroupSubscribers(java.lang.Long id) {
      super(Groupsubscribersendpoint.this, "GET", REST_PATH, null, com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetGroupSubscribers setAlt(java.lang.String alt) {
      return (GetGroupSubscribers) super.setAlt(alt);
    }

    @Override
    public GetGroupSubscribers setFields(java.lang.String fields) {
      return (GetGroupSubscribers) super.setFields(fields);
    }

    @Override
    public GetGroupSubscribers setKey(java.lang.String key) {
      return (GetGroupSubscribers) super.setKey(key);
    }

    @Override
    public GetGroupSubscribers setOauthToken(java.lang.String oauthToken) {
      return (GetGroupSubscribers) super.setOauthToken(oauthToken);
    }

    @Override
    public GetGroupSubscribers setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetGroupSubscribers) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetGroupSubscribers setQuotaUser(java.lang.String quotaUser) {
      return (GetGroupSubscribers) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetGroupSubscribers setUserIp(java.lang.String userIp) {
      return (GetGroupSubscribers) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetGroupSubscribers setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetGroupSubscribers set(String parameterName, Object value) {
      return (GetGroupSubscribers) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertGroupSubscribers".
   *
   * This request holds the parameters needed by the the groupsubscribersendpoint server.  After
   * setting any optional parameters, call the {@link InsertGroupSubscribers#execute()} method to
   * invoke the remote operation.
   *
   * @param content the {@link com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers}
   * @return the request
   */
  public InsertGroupSubscribers insertGroupSubscribers(com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers content) throws java.io.IOException {
    InsertGroupSubscribers result = new InsertGroupSubscribers(content);
    initialize(result);
    return result;
  }

  public class InsertGroupSubscribers extends GroupsubscribersendpointRequest<com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers> {

    private static final String REST_PATH = "groupsubscribers";

    /**
     * Create a request for the method "insertGroupSubscribers".
     *
     * This request holds the parameters needed by the the groupsubscribersendpoint server.  After
     * setting any optional parameters, call the {@link InsertGroupSubscribers#execute()} method to
     * invoke the remote operation. <p> {@link InsertGroupSubscribers#initialize(com.google.api.client
     * .googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers}
     * @since 1.13
     */
    protected InsertGroupSubscribers(com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers content) {
      super(Groupsubscribersendpoint.this, "POST", REST_PATH, content, com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers.class);
    }

    @Override
    public InsertGroupSubscribers setAlt(java.lang.String alt) {
      return (InsertGroupSubscribers) super.setAlt(alt);
    }

    @Override
    public InsertGroupSubscribers setFields(java.lang.String fields) {
      return (InsertGroupSubscribers) super.setFields(fields);
    }

    @Override
    public InsertGroupSubscribers setKey(java.lang.String key) {
      return (InsertGroupSubscribers) super.setKey(key);
    }

    @Override
    public InsertGroupSubscribers setOauthToken(java.lang.String oauthToken) {
      return (InsertGroupSubscribers) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertGroupSubscribers setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertGroupSubscribers) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertGroupSubscribers setQuotaUser(java.lang.String quotaUser) {
      return (InsertGroupSubscribers) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertGroupSubscribers setUserIp(java.lang.String userIp) {
      return (InsertGroupSubscribers) super.setUserIp(userIp);
    }

    @Override
    public InsertGroupSubscribers set(String parameterName, Object value) {
      return (InsertGroupSubscribers) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listGroupSubscribers".
   *
   * This request holds the parameters needed by the the groupsubscribersendpoint server.  After
   * setting any optional parameters, call the {@link ListGroupSubscribers#execute()} method to invoke
   * the remote operation.
   *
   * @return the request
   */
  public ListGroupSubscribers listGroupSubscribers() throws java.io.IOException {
    ListGroupSubscribers result = new ListGroupSubscribers();
    initialize(result);
    return result;
  }

  public class ListGroupSubscribers extends GroupsubscribersendpointRequest<com.shawnkrecker.eventation.groupsubscribersendpoint.model.CollectionResponseGroupSubscribers> {

    private static final String REST_PATH = "groupsubscribers";

    /**
     * Create a request for the method "listGroupSubscribers".
     *
     * This request holds the parameters needed by the the groupsubscribersendpoint server.  After
     * setting any optional parameters, call the {@link ListGroupSubscribers#execute()} method to
     * invoke the remote operation. <p> {@link ListGroupSubscribers#initialize(com.google.api.client.g
     * oogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListGroupSubscribers() {
      super(Groupsubscribersendpoint.this, "GET", REST_PATH, null, com.shawnkrecker.eventation.groupsubscribersendpoint.model.CollectionResponseGroupSubscribers.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListGroupSubscribers setAlt(java.lang.String alt) {
      return (ListGroupSubscribers) super.setAlt(alt);
    }

    @Override
    public ListGroupSubscribers setFields(java.lang.String fields) {
      return (ListGroupSubscribers) super.setFields(fields);
    }

    @Override
    public ListGroupSubscribers setKey(java.lang.String key) {
      return (ListGroupSubscribers) super.setKey(key);
    }

    @Override
    public ListGroupSubscribers setOauthToken(java.lang.String oauthToken) {
      return (ListGroupSubscribers) super.setOauthToken(oauthToken);
    }

    @Override
    public ListGroupSubscribers setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListGroupSubscribers) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListGroupSubscribers setQuotaUser(java.lang.String quotaUser) {
      return (ListGroupSubscribers) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListGroupSubscribers setUserIp(java.lang.String userIp) {
      return (ListGroupSubscribers) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListGroupSubscribers setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListGroupSubscribers setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListGroupSubscribers set(String parameterName, Object value) {
      return (ListGroupSubscribers) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeGroupSubscribers".
   *
   * This request holds the parameters needed by the the groupsubscribersendpoint server.  After
   * setting any optional parameters, call the {@link RemoveGroupSubscribers#execute()} method to
   * invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveGroupSubscribers removeGroupSubscribers(java.lang.Long id) throws java.io.IOException {
    RemoveGroupSubscribers result = new RemoveGroupSubscribers(id);
    initialize(result);
    return result;
  }

  public class RemoveGroupSubscribers extends GroupsubscribersendpointRequest<Void> {

    private static final String REST_PATH = "groupsubscribers/{id}";

    /**
     * Create a request for the method "removeGroupSubscribers".
     *
     * This request holds the parameters needed by the the groupsubscribersendpoint server.  After
     * setting any optional parameters, call the {@link RemoveGroupSubscribers#execute()} method to
     * invoke the remote operation. <p> {@link RemoveGroupSubscribers#initialize(com.google.api.client
     * .googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveGroupSubscribers(java.lang.Long id) {
      super(Groupsubscribersendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveGroupSubscribers setAlt(java.lang.String alt) {
      return (RemoveGroupSubscribers) super.setAlt(alt);
    }

    @Override
    public RemoveGroupSubscribers setFields(java.lang.String fields) {
      return (RemoveGroupSubscribers) super.setFields(fields);
    }

    @Override
    public RemoveGroupSubscribers setKey(java.lang.String key) {
      return (RemoveGroupSubscribers) super.setKey(key);
    }

    @Override
    public RemoveGroupSubscribers setOauthToken(java.lang.String oauthToken) {
      return (RemoveGroupSubscribers) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveGroupSubscribers setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveGroupSubscribers) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveGroupSubscribers setQuotaUser(java.lang.String quotaUser) {
      return (RemoveGroupSubscribers) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveGroupSubscribers setUserIp(java.lang.String userIp) {
      return (RemoveGroupSubscribers) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveGroupSubscribers setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveGroupSubscribers set(String parameterName, Object value) {
      return (RemoveGroupSubscribers) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateGroupSubscribers".
   *
   * This request holds the parameters needed by the the groupsubscribersendpoint server.  After
   * setting any optional parameters, call the {@link UpdateGroupSubscribers#execute()} method to
   * invoke the remote operation.
   *
   * @param content the {@link com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers}
   * @return the request
   */
  public UpdateGroupSubscribers updateGroupSubscribers(com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers content) throws java.io.IOException {
    UpdateGroupSubscribers result = new UpdateGroupSubscribers(content);
    initialize(result);
    return result;
  }

  public class UpdateGroupSubscribers extends GroupsubscribersendpointRequest<com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers> {

    private static final String REST_PATH = "groupsubscribers";

    /**
     * Create a request for the method "updateGroupSubscribers".
     *
     * This request holds the parameters needed by the the groupsubscribersendpoint server.  After
     * setting any optional parameters, call the {@link UpdateGroupSubscribers#execute()} method to
     * invoke the remote operation. <p> {@link UpdateGroupSubscribers#initialize(com.google.api.client
     * .googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers}
     * @since 1.13
     */
    protected UpdateGroupSubscribers(com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers content) {
      super(Groupsubscribersendpoint.this, "PUT", REST_PATH, content, com.shawnkrecker.eventation.groupsubscribersendpoint.model.GroupSubscribers.class);
    }

    @Override
    public UpdateGroupSubscribers setAlt(java.lang.String alt) {
      return (UpdateGroupSubscribers) super.setAlt(alt);
    }

    @Override
    public UpdateGroupSubscribers setFields(java.lang.String fields) {
      return (UpdateGroupSubscribers) super.setFields(fields);
    }

    @Override
    public UpdateGroupSubscribers setKey(java.lang.String key) {
      return (UpdateGroupSubscribers) super.setKey(key);
    }

    @Override
    public UpdateGroupSubscribers setOauthToken(java.lang.String oauthToken) {
      return (UpdateGroupSubscribers) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateGroupSubscribers setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateGroupSubscribers) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateGroupSubscribers setQuotaUser(java.lang.String quotaUser) {
      return (UpdateGroupSubscribers) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateGroupSubscribers setUserIp(java.lang.String userIp) {
      return (UpdateGroupSubscribers) super.setUserIp(userIp);
    }

    @Override
    public UpdateGroupSubscribers set(String parameterName, Object value) {
      return (UpdateGroupSubscribers) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Groupsubscribersendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Groupsubscribersendpoint}. */
    @Override
    public Groupsubscribersendpoint build() {
      return new Groupsubscribersendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GroupsubscribersendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGroupsubscribersendpointRequestInitializer(
        GroupsubscribersendpointRequestInitializer groupsubscribersendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(groupsubscribersendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
