/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-04 at 23:36:42 UTC 
 * Modify at your own risk.
 */

package com.shawnkrecker.eventation.subscriberendpoint;

/**
 * Service definition for Subscriberendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link SubscriberendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Subscriberendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the subscriberendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://event-ation.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "subscriberendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Subscriberendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Subscriberendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getSubscriber".
   *
   * This request holds the parameters needed by the the subscriberendpoint server.  After setting any
   * optional parameters, call the {@link GetSubscriber#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetSubscriber getSubscriber(java.lang.String id) throws java.io.IOException {
    GetSubscriber result = new GetSubscriber(id);
    initialize(result);
    return result;
  }

  public class GetSubscriber extends SubscriberendpointRequest<com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber> {

    private static final String REST_PATH = "subscriber/{id}";

    /**
     * Create a request for the method "getSubscriber".
     *
     * This request holds the parameters needed by the the subscriberendpoint server.  After setting
     * any optional parameters, call the {@link GetSubscriber#execute()} method to invoke the remote
     * operation. <p> {@link GetSubscriber#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetSubscriber(java.lang.String id) {
      super(Subscriberendpoint.this, "GET", REST_PATH, null, com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetSubscriber setAlt(java.lang.String alt) {
      return (GetSubscriber) super.setAlt(alt);
    }

    @Override
    public GetSubscriber setFields(java.lang.String fields) {
      return (GetSubscriber) super.setFields(fields);
    }

    @Override
    public GetSubscriber setKey(java.lang.String key) {
      return (GetSubscriber) super.setKey(key);
    }

    @Override
    public GetSubscriber setOauthToken(java.lang.String oauthToken) {
      return (GetSubscriber) super.setOauthToken(oauthToken);
    }

    @Override
    public GetSubscriber setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetSubscriber) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetSubscriber setQuotaUser(java.lang.String quotaUser) {
      return (GetSubscriber) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetSubscriber setUserIp(java.lang.String userIp) {
      return (GetSubscriber) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetSubscriber setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetSubscriber set(String parameterName, Object value) {
      return (GetSubscriber) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertSubscriber".
   *
   * This request holds the parameters needed by the the subscriberendpoint server.  After setting any
   * optional parameters, call the {@link InsertSubscriber#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber}
   * @return the request
   */
  public InsertSubscriber insertSubscriber(com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber content) throws java.io.IOException {
    InsertSubscriber result = new InsertSubscriber(content);
    initialize(result);
    return result;
  }

  public class InsertSubscriber extends SubscriberendpointRequest<com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber> {

    private static final String REST_PATH = "subscriber";

    /**
     * Create a request for the method "insertSubscriber".
     *
     * This request holds the parameters needed by the the subscriberendpoint server.  After setting
     * any optional parameters, call the {@link InsertSubscriber#execute()} method to invoke the
     * remote operation. <p> {@link InsertSubscriber#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber}
     * @since 1.13
     */
    protected InsertSubscriber(com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber content) {
      super(Subscriberendpoint.this, "POST", REST_PATH, content, com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber.class);
    }

    @Override
    public InsertSubscriber setAlt(java.lang.String alt) {
      return (InsertSubscriber) super.setAlt(alt);
    }

    @Override
    public InsertSubscriber setFields(java.lang.String fields) {
      return (InsertSubscriber) super.setFields(fields);
    }

    @Override
    public InsertSubscriber setKey(java.lang.String key) {
      return (InsertSubscriber) super.setKey(key);
    }

    @Override
    public InsertSubscriber setOauthToken(java.lang.String oauthToken) {
      return (InsertSubscriber) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertSubscriber setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertSubscriber) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertSubscriber setQuotaUser(java.lang.String quotaUser) {
      return (InsertSubscriber) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertSubscriber setUserIp(java.lang.String userIp) {
      return (InsertSubscriber) super.setUserIp(userIp);
    }

    @Override
    public InsertSubscriber set(String parameterName, Object value) {
      return (InsertSubscriber) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listSubscriber".
   *
   * This request holds the parameters needed by the the subscriberendpoint server.  After setting any
   * optional parameters, call the {@link ListSubscriber#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListSubscriber listSubscriber() throws java.io.IOException {
    ListSubscriber result = new ListSubscriber();
    initialize(result);
    return result;
  }

  public class ListSubscriber extends SubscriberendpointRequest<com.shawnkrecker.eventation.subscriberendpoint.model.CollectionResponseSubscriber> {

    private static final String REST_PATH = "subscriber";

    /**
     * Create a request for the method "listSubscriber".
     *
     * This request holds the parameters needed by the the subscriberendpoint server.  After setting
     * any optional parameters, call the {@link ListSubscriber#execute()} method to invoke the remote
     * operation. <p> {@link ListSubscriber#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListSubscriber() {
      super(Subscriberendpoint.this, "GET", REST_PATH, null, com.shawnkrecker.eventation.subscriberendpoint.model.CollectionResponseSubscriber.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListSubscriber setAlt(java.lang.String alt) {
      return (ListSubscriber) super.setAlt(alt);
    }

    @Override
    public ListSubscriber setFields(java.lang.String fields) {
      return (ListSubscriber) super.setFields(fields);
    }

    @Override
    public ListSubscriber setKey(java.lang.String key) {
      return (ListSubscriber) super.setKey(key);
    }

    @Override
    public ListSubscriber setOauthToken(java.lang.String oauthToken) {
      return (ListSubscriber) super.setOauthToken(oauthToken);
    }

    @Override
    public ListSubscriber setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListSubscriber) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListSubscriber setQuotaUser(java.lang.String quotaUser) {
      return (ListSubscriber) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListSubscriber setUserIp(java.lang.String userIp) {
      return (ListSubscriber) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListSubscriber setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListSubscriber setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListSubscriber set(String parameterName, Object value) {
      return (ListSubscriber) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeSubscriber".
   *
   * This request holds the parameters needed by the the subscriberendpoint server.  After setting any
   * optional parameters, call the {@link RemoveSubscriber#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveSubscriber removeSubscriber(java.lang.String id) throws java.io.IOException {
    RemoveSubscriber result = new RemoveSubscriber(id);
    initialize(result);
    return result;
  }

  public class RemoveSubscriber extends SubscriberendpointRequest<Void> {

    private static final String REST_PATH = "subscriber/{id}";

    /**
     * Create a request for the method "removeSubscriber".
     *
     * This request holds the parameters needed by the the subscriberendpoint server.  After setting
     * any optional parameters, call the {@link RemoveSubscriber#execute()} method to invoke the
     * remote operation. <p> {@link RemoveSubscriber#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveSubscriber(java.lang.String id) {
      super(Subscriberendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveSubscriber setAlt(java.lang.String alt) {
      return (RemoveSubscriber) super.setAlt(alt);
    }

    @Override
    public RemoveSubscriber setFields(java.lang.String fields) {
      return (RemoveSubscriber) super.setFields(fields);
    }

    @Override
    public RemoveSubscriber setKey(java.lang.String key) {
      return (RemoveSubscriber) super.setKey(key);
    }

    @Override
    public RemoveSubscriber setOauthToken(java.lang.String oauthToken) {
      return (RemoveSubscriber) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveSubscriber setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveSubscriber) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveSubscriber setQuotaUser(java.lang.String quotaUser) {
      return (RemoveSubscriber) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveSubscriber setUserIp(java.lang.String userIp) {
      return (RemoveSubscriber) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveSubscriber setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveSubscriber set(String parameterName, Object value) {
      return (RemoveSubscriber) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateSubscriber".
   *
   * This request holds the parameters needed by the the subscriberendpoint server.  After setting any
   * optional parameters, call the {@link UpdateSubscriber#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber}
   * @return the request
   */
  public UpdateSubscriber updateSubscriber(com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber content) throws java.io.IOException {
    UpdateSubscriber result = new UpdateSubscriber(content);
    initialize(result);
    return result;
  }

  public class UpdateSubscriber extends SubscriberendpointRequest<com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber> {

    private static final String REST_PATH = "subscriber";

    /**
     * Create a request for the method "updateSubscriber".
     *
     * This request holds the parameters needed by the the subscriberendpoint server.  After setting
     * any optional parameters, call the {@link UpdateSubscriber#execute()} method to invoke the
     * remote operation. <p> {@link UpdateSubscriber#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber}
     * @since 1.13
     */
    protected UpdateSubscriber(com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber content) {
      super(Subscriberendpoint.this, "PUT", REST_PATH, content, com.shawnkrecker.eventation.subscriberendpoint.model.Subscriber.class);
    }

    @Override
    public UpdateSubscriber setAlt(java.lang.String alt) {
      return (UpdateSubscriber) super.setAlt(alt);
    }

    @Override
    public UpdateSubscriber setFields(java.lang.String fields) {
      return (UpdateSubscriber) super.setFields(fields);
    }

    @Override
    public UpdateSubscriber setKey(java.lang.String key) {
      return (UpdateSubscriber) super.setKey(key);
    }

    @Override
    public UpdateSubscriber setOauthToken(java.lang.String oauthToken) {
      return (UpdateSubscriber) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateSubscriber setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateSubscriber) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateSubscriber setQuotaUser(java.lang.String quotaUser) {
      return (UpdateSubscriber) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateSubscriber setUserIp(java.lang.String userIp) {
      return (UpdateSubscriber) super.setUserIp(userIp);
    }

    @Override
    public UpdateSubscriber set(String parameterName, Object value) {
      return (UpdateSubscriber) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Subscriberendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Subscriberendpoint}. */
    @Override
    public Subscriberendpoint build() {
      return new Subscriberendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link SubscriberendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setSubscriberendpointRequestInitializer(
        SubscriberendpointRequestInitializer subscriberendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(subscriberendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
