/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-04 at 23:36:16 UTC 
 * Modify at your own risk.
 */

package com.shawnkrecker.eventation.groupendpoint.model;

/**
 * Model definition for Group.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the groupendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Group extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String adminName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String groupDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String groupName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numSubscribers;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAdminName() {
    return adminName;
  }

  /**
   * @param adminName adminName or {@code null} for none
   */
  public Group setAdminName(java.lang.String adminName) {
    this.adminName = adminName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroupDescription() {
    return groupDescription;
  }

  /**
   * @param groupDescription groupDescription or {@code null} for none
   */
  public Group setGroupDescription(java.lang.String groupDescription) {
    this.groupDescription = groupDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroupName() {
    return groupName;
  }

  /**
   * @param groupName groupName or {@code null} for none
   */
  public Group setGroupName(java.lang.String groupName) {
    this.groupName = groupName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumSubscribers() {
    return numSubscribers;
  }

  /**
   * @param numSubscribers numSubscribers or {@code null} for none
   */
  public Group setNumSubscribers(java.lang.Integer numSubscribers) {
    this.numSubscribers = numSubscribers;
    return this;
  }

  @Override
  public Group set(String fieldName, Object value) {
    return (Group) super.set(fieldName, value);
  }

  @Override
  public Group clone() {
    return (Group) super.clone();
  }

}
