/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-04 at 23:36:16 UTC 
 * Modify at your own risk.
 */

package com.shawnkrecker.eventation.groupendpoint;

/**
 * Service definition for Groupendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GroupendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Groupendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the groupendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://event-ation.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "groupendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Groupendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Groupendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getGroup".
   *
   * This request holds the parameters needed by the the groupendpoint server.  After setting any
   * optional parameters, call the {@link GetGroup#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetGroup getGroup(java.lang.String id) throws java.io.IOException {
    GetGroup result = new GetGroup(id);
    initialize(result);
    return result;
  }

  public class GetGroup extends GroupendpointRequest<com.shawnkrecker.eventation.groupendpoint.model.Group> {

    private static final String REST_PATH = "group/{id}";

    /**
     * Create a request for the method "getGroup".
     *
     * This request holds the parameters needed by the the groupendpoint server.  After setting any
     * optional parameters, call the {@link GetGroup#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetGroup#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetGroup(java.lang.String id) {
      super(Groupendpoint.this, "GET", REST_PATH, null, com.shawnkrecker.eventation.groupendpoint.model.Group.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetGroup setAlt(java.lang.String alt) {
      return (GetGroup) super.setAlt(alt);
    }

    @Override
    public GetGroup setFields(java.lang.String fields) {
      return (GetGroup) super.setFields(fields);
    }

    @Override
    public GetGroup setKey(java.lang.String key) {
      return (GetGroup) super.setKey(key);
    }

    @Override
    public GetGroup setOauthToken(java.lang.String oauthToken) {
      return (GetGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public GetGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetGroup setQuotaUser(java.lang.String quotaUser) {
      return (GetGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetGroup setUserIp(java.lang.String userIp) {
      return (GetGroup) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetGroup setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetGroup set(String parameterName, Object value) {
      return (GetGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertGroup".
   *
   * This request holds the parameters needed by the the groupendpoint server.  After setting any
   * optional parameters, call the {@link InsertGroup#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.shawnkrecker.eventation.groupendpoint.model.Group}
   * @return the request
   */
  public InsertGroup insertGroup(com.shawnkrecker.eventation.groupendpoint.model.Group content) throws java.io.IOException {
    InsertGroup result = new InsertGroup(content);
    initialize(result);
    return result;
  }

  public class InsertGroup extends GroupendpointRequest<com.shawnkrecker.eventation.groupendpoint.model.Group> {

    private static final String REST_PATH = "group";

    /**
     * Create a request for the method "insertGroup".
     *
     * This request holds the parameters needed by the the groupendpoint server.  After setting any
     * optional parameters, call the {@link InsertGroup#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertGroup#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.shawnkrecker.eventation.groupendpoint.model.Group}
     * @since 1.13
     */
    protected InsertGroup(com.shawnkrecker.eventation.groupendpoint.model.Group content) {
      super(Groupendpoint.this, "POST", REST_PATH, content, com.shawnkrecker.eventation.groupendpoint.model.Group.class);
    }

    @Override
    public InsertGroup setAlt(java.lang.String alt) {
      return (InsertGroup) super.setAlt(alt);
    }

    @Override
    public InsertGroup setFields(java.lang.String fields) {
      return (InsertGroup) super.setFields(fields);
    }

    @Override
    public InsertGroup setKey(java.lang.String key) {
      return (InsertGroup) super.setKey(key);
    }

    @Override
    public InsertGroup setOauthToken(java.lang.String oauthToken) {
      return (InsertGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertGroup setQuotaUser(java.lang.String quotaUser) {
      return (InsertGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertGroup setUserIp(java.lang.String userIp) {
      return (InsertGroup) super.setUserIp(userIp);
    }

    @Override
    public InsertGroup set(String parameterName, Object value) {
      return (InsertGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listGroup".
   *
   * This request holds the parameters needed by the the groupendpoint server.  After setting any
   * optional parameters, call the {@link ListGroup#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListGroup listGroup() throws java.io.IOException {
    ListGroup result = new ListGroup();
    initialize(result);
    return result;
  }

  public class ListGroup extends GroupendpointRequest<com.shawnkrecker.eventation.groupendpoint.model.CollectionResponseGroup> {

    private static final String REST_PATH = "group";

    /**
     * Create a request for the method "listGroup".
     *
     * This request holds the parameters needed by the the groupendpoint server.  After setting any
     * optional parameters, call the {@link ListGroup#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListGroup#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListGroup() {
      super(Groupendpoint.this, "GET", REST_PATH, null, com.shawnkrecker.eventation.groupendpoint.model.CollectionResponseGroup.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListGroup setAlt(java.lang.String alt) {
      return (ListGroup) super.setAlt(alt);
    }

    @Override
    public ListGroup setFields(java.lang.String fields) {
      return (ListGroup) super.setFields(fields);
    }

    @Override
    public ListGroup setKey(java.lang.String key) {
      return (ListGroup) super.setKey(key);
    }

    @Override
    public ListGroup setOauthToken(java.lang.String oauthToken) {
      return (ListGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public ListGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListGroup setQuotaUser(java.lang.String quotaUser) {
      return (ListGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListGroup setUserIp(java.lang.String userIp) {
      return (ListGroup) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListGroup setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListGroup setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListGroup set(String parameterName, Object value) {
      return (ListGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeGroup".
   *
   * This request holds the parameters needed by the the groupendpoint server.  After setting any
   * optional parameters, call the {@link RemoveGroup#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveGroup removeGroup(java.lang.String id) throws java.io.IOException {
    RemoveGroup result = new RemoveGroup(id);
    initialize(result);
    return result;
  }

  public class RemoveGroup extends GroupendpointRequest<Void> {

    private static final String REST_PATH = "group/{id}";

    /**
     * Create a request for the method "removeGroup".
     *
     * This request holds the parameters needed by the the groupendpoint server.  After setting any
     * optional parameters, call the {@link RemoveGroup#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveGroup#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveGroup(java.lang.String id) {
      super(Groupendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveGroup setAlt(java.lang.String alt) {
      return (RemoveGroup) super.setAlt(alt);
    }

    @Override
    public RemoveGroup setFields(java.lang.String fields) {
      return (RemoveGroup) super.setFields(fields);
    }

    @Override
    public RemoveGroup setKey(java.lang.String key) {
      return (RemoveGroup) super.setKey(key);
    }

    @Override
    public RemoveGroup setOauthToken(java.lang.String oauthToken) {
      return (RemoveGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveGroup setQuotaUser(java.lang.String quotaUser) {
      return (RemoveGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveGroup setUserIp(java.lang.String userIp) {
      return (RemoveGroup) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveGroup setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveGroup set(String parameterName, Object value) {
      return (RemoveGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateGroup".
   *
   * This request holds the parameters needed by the the groupendpoint server.  After setting any
   * optional parameters, call the {@link UpdateGroup#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.shawnkrecker.eventation.groupendpoint.model.Group}
   * @return the request
   */
  public UpdateGroup updateGroup(com.shawnkrecker.eventation.groupendpoint.model.Group content) throws java.io.IOException {
    UpdateGroup result = new UpdateGroup(content);
    initialize(result);
    return result;
  }

  public class UpdateGroup extends GroupendpointRequest<com.shawnkrecker.eventation.groupendpoint.model.Group> {

    private static final String REST_PATH = "group";

    /**
     * Create a request for the method "updateGroup".
     *
     * This request holds the parameters needed by the the groupendpoint server.  After setting any
     * optional parameters, call the {@link UpdateGroup#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateGroup#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.shawnkrecker.eventation.groupendpoint.model.Group}
     * @since 1.13
     */
    protected UpdateGroup(com.shawnkrecker.eventation.groupendpoint.model.Group content) {
      super(Groupendpoint.this, "PUT", REST_PATH, content, com.shawnkrecker.eventation.groupendpoint.model.Group.class);
    }

    @Override
    public UpdateGroup setAlt(java.lang.String alt) {
      return (UpdateGroup) super.setAlt(alt);
    }

    @Override
    public UpdateGroup setFields(java.lang.String fields) {
      return (UpdateGroup) super.setFields(fields);
    }

    @Override
    public UpdateGroup setKey(java.lang.String key) {
      return (UpdateGroup) super.setKey(key);
    }

    @Override
    public UpdateGroup setOauthToken(java.lang.String oauthToken) {
      return (UpdateGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateGroup setQuotaUser(java.lang.String quotaUser) {
      return (UpdateGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateGroup setUserIp(java.lang.String userIp) {
      return (UpdateGroup) super.setUserIp(userIp);
    }

    @Override
    public UpdateGroup set(String parameterName, Object value) {
      return (UpdateGroup) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Groupendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Groupendpoint}. */
    @Override
    public Groupendpoint build() {
      return new Groupendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GroupendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGroupendpointRequestInitializer(
        GroupendpointRequestInitializer groupendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(groupendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
